// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pg_org_defaultrole;

namespace pg_org_defaultrole.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20200812093315_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("pg_org_defaultrole.Org", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("DefaultRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Orgs");
                });

            modelBuilder.Entity("pg_org_defaultrole.Role", b =>
                {
                    b.Property<int>("OrgId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int?>("OrgId1")
                        .HasColumnType("integer");

                    b.HasKey("OrgId", "Id");

                    b.HasIndex("OrgId1")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("pg_org_defaultrole.Role", b =>
                {
                    b.HasOne("pg_org_defaultrole.Org", "Org")
                        .WithMany("Roles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("pg_org_defaultrole.Org", null)
                        .WithOne("DefaultRole")
                        .HasForeignKey("pg_org_defaultrole.Role", "OrgId1");
                });
#pragma warning restore 612, 618
        }
    }
}
