// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pg_org_defaultrole;

namespace pg_org_defaultrole.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20200812101414_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("pg_org_defaultrole.Org", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRoleId")
                        .HasColumnName("default_role_id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("pk_orgs");

                    b.HasIndex("Id", "DefaultRoleId")
                        .IsUnique()
                        .HasName("ix_orgs_id_default_role_id");

                    b.ToTable("orgs");
                });

            modelBuilder.Entity("pg_org_defaultrole.Role", b =>
                {
                    b.Property<int>("OrgId")
                        .HasColumnName("org_id")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnName("id")
                        .HasColumnType("integer");

                    b.HasKey("OrgId", "Id")
                        .HasName("pk_roles");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("pg_org_defaultrole.Org", b =>
                {
                    b.HasOne("pg_org_defaultrole.Role", "DefaultRole")
                        .WithOne()
                        .HasForeignKey("pg_org_defaultrole.Org", "Id", "DefaultRoleId")
                        .HasConstraintName("fk_orgs_roles_id_default_role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pg_org_defaultrole.Role", b =>
                {
                    b.HasOne("pg_org_defaultrole.Org", "Org")
                        .WithMany("Roles")
                        .HasForeignKey("OrgId")
                        .HasConstraintName("fk_roles_orgs_org_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
