// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pg_org_defaultrole;

namespace pg_org_defaultrole.Migrations
{
    [DbContext(typeof(AppContext))]
    partial class AppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("pg_org_defaultrole.Org", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("DefaultRoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id", "DefaultRoleId")
                        .IsUnique();

                    b.ToTable("Orgs");
                });

            modelBuilder.Entity("pg_org_defaultrole.Role", b =>
                {
                    b.Property<int>("OrgId")
                        .HasColumnType("integer");

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("OrgId", "Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("pg_org_defaultrole.Org", b =>
                {
                    b.HasOne("pg_org_defaultrole.Role", "DefaultRole")
                        .WithOne()
                        .HasForeignKey("pg_org_defaultrole.Org", "Id", "DefaultRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("pg_org_defaultrole.Role", b =>
                {
                    b.HasOne("pg_org_defaultrole.Org", "Org")
                        .WithMany("Roles")
                        .HasForeignKey("OrgId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
