version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=pwd

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 54321:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=guest
      - PGADMIN_DEFAULT_PASSWORD=pwd
      - GUNICORN_ACCESS_LOGFILE=/var/lib/pgadmin/log.txt
