// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using pg_id_not_updated;

#nullable disable

namespace pg_id_not_updated.Migrations
{
    [DbContext(typeof(TestContext))]
    partial class TestContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("pg_id_not_updated.Role", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("TenantId", "Id")
                        .HasName("pk_roles");

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("pg_id_not_updated.Tenant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<int>("Id"));

                    b.Property<int?>("DefaultRoleId")
                        .HasColumnType("integer")
                        .HasColumnName("default_role_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Id", "DefaultRoleId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_id_default_role_id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("pg_id_not_updated.Role", b =>
                {
                    b.HasOne("pg_id_not_updated.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_roles_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("pg_id_not_updated.Tenant", b =>
                {
                    b.HasOne("pg_id_not_updated.Role", "DefaultRole")
                        .WithOne()
                        .HasForeignKey("pg_id_not_updated.Tenant", "Id", "DefaultRoleId")
                        .HasConstraintName("fk_tenants_roles_id_default_role_id");

                    b.Navigation("DefaultRole");
                });
#pragma warning restore 612, 618
        }
    }
}
