version: "3"
services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=guest
      - POSTGRES_PASSWORD=pwd

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "6831:6831/udp" # trace ingestion
      - 16686:16686 # web ui
